stages:
  fetch_hidro:
    cmd: |
      poetry run python src/data/fetch_hidro_data.py
      git commit -am "Updated raw hidro data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/data/fetch_hidro_data.py
    params:
      - fetch.hidro_url
    outs:
      - data/raw/hidro/hidro_data.xml
    always_changed: true

  preprocess_hidro:
    cmd: |
      poetry run python src/data/preprocess_hidro_data.py
      git commit -am "Updated preprocessed hidro data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/data/preprocess_hidro_data.py
      - data/raw/hidro/hidro_data.xml
    params:
      - stations.hidro_stations
    outs:
      - data/preprocessed/hidro:
          persist: true

  fetch_weather:
    cmd: |
      poetry run python src/data/fetch_weather_data.py
      git commit -am "Updated raw weather data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/data/fetch_weather_data.py
    params:
      - fetch.weather_url
    outs:
      - data/raw/weather/weather_data.xml
    always_changed: true

  preprocess_weather:
    cmd: |
      poetry run python src/data/preprocess_weather_data.py
      git commit -am "Updated preprocessed weather data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/data/preprocess_weather_data.py
      - data/raw/weather/weather_data.xml
    params:
      - stations.weather_stations
    outs:
      - data/preprocessed/weather:
          persist: true

  validate_data:
    cmd: poetry run python gx/run_checkpoint.py
    deps:
      - data/preprocessed/hidro
      - data/preprocessed/weather
      - gx/run_checkpoint.py
      - gx/expectations/hidro_suite.json
      - gx/expectations/weather_suite.json
      - gx/great_expectations.yml
    outs:
      - gx/uncommitted/data_docs:
          persist: true

  test_data:
    cmd: poetry run python src/data/test_data.py
    deps:
      - data/preprocessed/hidro
      - data/preprocessed/weather
      - src/data/test_data.py
    outs:
      - data/reference/hidro:
          persist: true
      - data/reference/weather:
          persist: true
      - reports/data_testing:
          persist: true

  train_hidro:
    cmd: |
      poetry run python -m src.model.train_hidro_global
      git commit -am "Updated hidro global model on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/model/preprocess.py
      - src/model/train_hidro_global.py
      - data/preprocessed/hidro
      - gx/uncommitted/data_docs
      - data/reference/hidro
    params:
      - train.hidro_input_dir
      - train.global_models_output_dir
      - train.target_col
      - train.feature_cols
      - train.window_size
      - train.test_size
      - train.epochs
      - train.batch_size
      - train.min_rows
    outs:
      - models/hidro_global:
          persist: true

  train_risk_classifier:
    cmd: |
      poetry run python -m src.model.train_risk_classifier
      git commit -am "Updated risk classifier model on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/model/train_risk_classifier.py
      - data/preprocessed/hidro
      - data/preprocessed/weather
      - gx/uncommitted/data_docs
      - data/reference/hidro
      - data/reference/weather
    params:
      - train.hidro_input_dir
      - train.weather_input_dir
      - train.risk_models_output_dir
      - train.feature_cols
      - train.test_size
      - train.min_rows
    outs:
      - models/risk:
          persist: true

  prepare_production_data:
    cmd: poetry run python src/data/make_production_data.py
    deps:
      - src/data/make_production_data.py
      - data/preprocessed/hidro
      - data/preprocessed/weather
      - reports/modeling/risk_classifier_used_station_mapping.csv
    outs:
      - data/production/hidro:
          persist: true
      - data/production/weather:
          persist: true

  export_onnx:
    cmd: poetry run python -m src.model.export.export_onnx
    deps:
      - src/model/export/export_onnx.py
      - models/hidro_global/model_hidro_global.keras
      - models/risk/risk_classifier.keras
    outs:
      - models/onnx:
          persist: true
