name: Test data and deploy Evidently reports

on:
  workflow_dispatch:

jobs:
  test-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Evidently tests
        run: poetry run python src/data/test_data.py

      - name: Deploy Evidently reports to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./reports/data_testing
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Evidently data testing reports"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
